"""
src/explainer.py — Attribute-level match explanations via CLIP zero-shot text scoring.

Uses pre-computed catalog attribute labels from catalog_attributes.json
(generated by offline_indexer.py) — never re-fetches catalog images at runtime.

For scene crops, classifies attributes on-the-fly via CLIP text scoring.
Then compares scene attributes vs. pre-computed catalog attributes to
generate human-readable explanations.

Attribute vocabulary:
- color:    14 options (red, blue, black, white, green, yellow, pink, brown, gray, beige, multicolor, navy, orange, purple)
- pattern:  10 options (solid, striped, floral, checkered, polka dot, graphic print, abstract, animal print, plaid, tie-dye)
- category: 12 options (dress, top, pants, skirt, jacket, shoes, handbag, accessory, coat, shorts, sweater, jumpsuit)
- style:    10 options (casual, formal, sporty, bohemian, minimalist, vintage, streetwear, elegant, preppy, edgy)
"""

import json
import os
import numpy as np
from src.embedder import embed_texts

ARTIFACTS_DIR = "artifacts"

# Expanded attribute vocabulary (v2 — more options than v1)
ATTRIBUTES = {
    "color": [
        "red", "blue", "black", "white", "green", "yellow",
        "pink", "brown", "gray", "beige", "multicolor", "navy",
        "orange", "purple",
    ],
    "pattern": [
        "solid", "striped", "floral", "checkered", "polka dot",
        "graphic print", "abstract", "animal print", "plaid", "tie-dye",
    ],
    "category": [
        "dress", "top", "pants", "skirt", "jacket", "shoes",
        "handbag", "accessory", "coat", "shorts", "sweater", "jumpsuit",
    ],
    "style": [
        "casual", "formal", "sporty", "bohemian", "minimalist",
        "vintage", "streetwear", "elegant", "preppy", "edgy",
    ],
}


def _load_catalog_attributes():
    """Load pre-computed attribute labels for catalog products."""
    path = os.path.join(ARTIFACTS_DIR, "catalog_attributes.json")
    if os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    else:
        print("Warning: catalog_attributes.json not found. Explanations will be limited.")
        return {}


# Load pre-computed catalog attribute labels (set by offline_indexer.py)
_catalog_attributes = _load_catalog_attributes()

# Pre-compute CLIP text embeddings for each attribute option — done once at import
_attr_text_embs: dict = {}
for _attr, _options in ATTRIBUTES.items():
    _prompts = [f"a {opt} fashion item" for opt in _options]
    _attr_text_embs[_attr] = (_options, embed_texts(_prompts))


def classify_scene_attribute(scene_embedding: np.ndarray, attr: str) -> str:
    """
    Classify a scene crop embedding for a given attribute via CLIP text scoring.

    Args:
        scene_embedding: shape (512,) float32, L2-normalized
        attr: attribute key (one of: color, pattern, category, style)

    Returns:
        Best-matching attribute option (e.g., "red", "floral", "dress", "casual")
    """
    options, text_embs = _attr_text_embs[attr]
    scores = scene_embedding @ text_embs.T
    return options[int(np.argmax(scores))]


def explain_match(
    scene_embedding: np.ndarray,
    product_id: str,
    similarity_score: float,
    is_full_person: bool = False,
) -> str:
    """
    Generate a human-readable explanation for a scene → catalog match.

    Uses:
    - CLIP zero-shot text scoring to classify scene crop attributes
    - Pre-computed attribute labels for catalog product (no re-fetch needed)

    Args:
        scene_embedding: shape (512,) float32, L2-normalized
        product_id: catalog product signature hash
        similarity_score: cosine similarity score
        is_full_person: True when the scene crop is a whole-person bounding box

    Returns:
        Human-readable explanation string
    """
    catalog_attrs = _catalog_attributes.get(product_id, {})
    if not catalog_attrs:
        return f"Visual similarity score: {similarity_score:.2f}."

    shared = []
    different = []
    for attr in ATTRIBUTES:
        scene_val = classify_scene_attribute(scene_embedding, attr)
        catalog_val = catalog_attrs.get(attr, "")
        if scene_val == catalog_val:
            shared.append(f"{scene_val} {attr}")
        elif catalog_val:
            different.append(f"{attr}: scene={scene_val}, product={catalog_val}")

    parts = [f"Visual similarity: {similarity_score:.2f}."]
    if is_full_person:
        parts.append("Note: matched against full outfit (individual item detection unavailable).")
    if shared:
        parts.append("Shared attributes: " + ", ".join(shared) + ".")
    if different and len(different) <= 2:
        parts.append("Differences: " + "; ".join(different) + ".")

    return " ".join(parts)
